SUPERSECTOR_NAME_MAP = {
    1: "Agricultura, ganadería, aprovechamiento forestal, pesca y caza",
    2: "Industrias extractivas, energía, agua, gas y construcción",
    3: "Industrias manufactureras",
    4: "Comercio, transporte y almacenamiento",
    5: "Información en medios masivos, servicios financieros e inmobiliarios, profesionales y corporativos",
    6: "Servicios educativos, de salud y de asistencia social",
    7: "Servicios de esparcimiento, culturales, deportivos, alojamiento y alimentos",
    8: "Otros servicios excepto actividades gubernamentales",
    9: "Actividades gubernamentales",
}

SECTOR_NAME_MAP = {
    11: "Agricultura y ganadería",
    21: "Minería",
    22: "Energía eléctrica, agua y gas",
    23: "Construcción",
    31: "Industrias manufactureras (alimentos y textiles)",
    32: "Industrias manufactureras (madera, papel y químicos)",
    33: "Industrias manufactureras (metales, maquinaria y electrónicos)",
    43: "Comercio al por mayor",
    46: "Comercio al por menor",
    48: "Transporte y almacenamiento",
    49: "Correos",
    51: "Información en medios masivos",
    52: "Servicios financieros y de seguros",
    53: "Servicios inmobiliarios y de alquiler",
    54: "Servicios profesionales, científicos y técnicos",
    55: "Corporativos",
    56: "Servicios de apoyo a los negocios y manejo de desechos",
    61: "Servicios educativos",
    62: "Servicios de salud y de asistencia social",
    71: "Servicios de esparcimiento, culturales y deportivos",
    72: "Servicios de alojamiento temporal y de preparación de alimentos y bebidas",
    81: "Otros servicios excepto actividades gubernamentales",
    93: "Administración pública, defensa y seguridad social",
}

SECTOR_NAME_MAP_SHORT = {
    11: "Agricultura y\nganadería",
    21: "Minería",
    22: "Energía eléctrica,\nagua y gas",
    23: "Construcción",
    31: "Manufactura (alimentos\ny textiles)",
    32: "Manufactura (madera,\npapel y químicos)",
    33: "Manufactura (metales,\nmaquinaria y electrónicos)",
    43: "Comercio al\npor mayor",
    46: "Comercio al\npor menor",
    48: "Transporte y\nalmacenamiento",
    49: "Correos",
    51: "Medios masivos",
    52: "Financieros y\nde seguros",
    53: "Inmobiliarios\ny de alquiler",
    54: "Profesionales,\ncientíficos y técnicos",
    55: "Corporativos",
    56: "Apoyo a los negocios\ny manejo de desechos",
    61: "Educativos",
    62: "Salud y\nasistencia social",
    71: "Esparcimiento, act.\nculturales y deportivas",
    72: "Hoteles y\nrestaurantes",
    81: "Otros ",
    93: "Admon. pública\ny defensa ",
}

SUBSECTOR_NAME_MAP = {
    111: "Agricultura",
    112: "Cría y explotación de animales",
    113: "Aprovechamiento forestal",
    114: "Pesca, caza y captura",
    115: "Servicios relacionados con las actividades agropecuarias y forestales",
    211: "Extracción de petróleo y gas",
    212: "Minería de minerales metálicos y no metálicos, excepto petróleo y gas",
    213: "Servicios relacionados con la minería",
    221: "Generación, transmisión, distribución y comercialización de energía eléctrica, suministro de agua y de gas natural por ductos al consumidor final",
    236: "Edificación",
    237: "Construcción de obras de ingeniería civil",
    238: "Trabajos especializados para la construcción",
    311: "Industria alimentaria",
    312: "Industria de las bebidas y del tabaco",
    313: "Fabricación de insumos textiles y acabado de textiles",
    314: "Fabricación de productos textiles, excepto prendas de vestir",
    315: "Fabricación de prendas de vestir",
    316: "Curtido y acabado de cuero y piel, y fabricación de productos de cuero, piel y materiales sucedáneos",
    321: "Industria de la madera",
    322: "Industria del papel",
    323: "Impresión e industrias conexas",
    324: "Fabricación de productos derivados del petróleo y del carbón",
    325: "Industria química",
    326: "Industria del plástico y del hule",
    327: "Fabricación de productos a base de minerales no metálicos",
    331: "Industrias metálicas básicas",
    332: "Fabricación de productos metálicos",
    333: "Fabricación de maquinaria y equipo",
    334: "Fabricación de equipo de computación, comunicación, medición y de otros equipos, componentes y accesorios electrónicos",
    335: "Fabricación de accesorios, aparatos eléctricos y equipo de generación de energía eléctrica",
    336: "Fabricación de equipo de transporte",
    337: "Fabricación de muebles, colchones y persianas",
    339: "Otras industrias manufactureras",
    431: "Comercio al por mayor de abarrotes, alimentos, bebidas, hielo y tabaco",
    432: "Comercio al por mayor de productos textiles y calzado",
    433: "Comercio al por mayor de productos farmacéuticos, de perfumería, artículos para el esparcimiento, electrodomésticos menores y aparatos de línea blanca",
    434: "Comercio al por mayor de materias primas agropecuarias y forestales, para la industria, y materiales de desecho",
    435: "Comercio al por mayor de maquinaria, equipo y mobiliario para actividades agropecuarias, industriales, de servicios y comerciales, y de otra maquinaria y equipo de uso general",
    436: "Comercio al por mayor de camiones y de partes y refacciones nuevas para automóviles, camionetas y camiones",
    437: "Intermediación de comercio al por mayor",
    461: "Comercio al por menor de abarrotes, alimentos, bebidas, hielo y tabaco",
    462: "Comercio al por menor en tiendas de autoservicio y departamentales",
    463: "Comercio al por menor de productos textiles, bisutería, accesorios de vestir y calzado",
    464: "Comercio al por menor de artículos para el cuidado de la salud",
    465: "Comercio al por menor de artículos de papelería, para el esparcimiento y otros artículos de uso personal",
    466: "Comercio al por menor de enseres domésticos, computadoras, artículos para la decoración de interiores y artículos usados",
    467: "Comercio al por menor de artículos de ferretería, tlapalería y vidrios",
    468: "Comercio al por menor de vehículos de motor, refacciones, combustibles y lubricantes",
    469: "Intermediación de comercio al por menor, y comercio al por menor a través de catálogos impresos, televisión y similares",
    481: "Transporte aéreo",
    482: "Transporte por ferrocarril",
    483: "Transporte por agua",
    484: "Autotransporte de carga",
    485: "Transporte terrestre de pasajeros, excepto por ferrocarril",
    486: "Transporte por ductos",
    487: "Transporte turístico",
    488: "Servicios relacionados con el transporte",
    491: "Servicios postales",
    492: "Servicios de mensajería y paquetería",
    493: "Servicios de almacenamiento",
    512: "Industria fílmica y del video, e industria del sonido",
    513: "Edición de periódicos, revistas, libros, directorios, software y otros materiales",
    516: "Radio y televisión y provisión de contenido",
    517: "Telecomunicaciones",
    518: "Provisión de infraestructura de servicios de cómputo, procesamiento de datos, hospedaje de páginas de internet y otros servicios relacionados",
    519: "Bibliotecas, archivos, portales de búsqueda en la red y otros servicios de suministro de información",
    521: "Banca central",
    522: "Instituciones de intermediación crediticia y financiera no bursátil",
    523: "Actividades bursátiles, cambiarias y de inversión financiera",
    524: "Compañías de seguros, fianzas, y administración de fondos para el retiro",
    525: "Sociedades de inversión especializadas en fondos para el retiro y fondos de inversión",
    531: "Servicios inmobiliarios",
    532: "Servicios de alquiler de bienes muebles",
    533: "Servicios de alquiler de marcas registradas, patentes y franquicias",
    541: "Servicios profesionales, científicos y técnicos",
    551: "Dirección y administración de grupos empresariales o corporativos",
    561: "Servicios de apoyo a los negocios",
    562: "Manejo de residuos y servicios de remediación",
    611: "Servicios educativos",
    621: "Servicios médicos de consulta externa y servicios relacionados",
    622: "Hospitales",
    623: "Residencias de asistencia social y para el cuidado de la salud",
    624: "Otros servicios de asistencia social",
    711: "Servicios artísticos, culturales y deportivos, y otros servicios relacionados",
    712: "Museos, sitios históricos, zoológicos y similares",
    713: "Servicios de entretenimiento en instalaciones recreativas y otros servicios recreativos",
    721: "Servicios de alojamiento temporal",
    722: "Servicios de preparación de alimentos y bebidas",
    811: "Servicios de reparación y mantenimiento",
    812: "Servicios personales",
    813: "Asociaciones y organizaciones",
    814: "Hogares con empleados domésticos",
    931: "Actividades legislativas, gubernamentales y de impartición de justicia",
    932: "Organismos internacionales y extraterritoriales",
}
